# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoshs_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_screenshot',
            field=models.ImageField(default='', upload_to=b'website_images'),
            preserve_default=False,
        ),
    ]
